### ISSUE TITLE
Segmentation fault in Doubly linked list .

### ISSUE THREAD

**Issue by Aswan-A** [Swassyman/just-college-code-files#1]
If we use insert at any position and give a position greater than the LL size it shows segmentation fault . 
![](https://github.com/user-attachments/assets/e98c6c7b-056e-4c19-9259-9e0f15ad90c7)

**Comment by Swassyman** [comment]
ayin

**Comment by Swassyman** [comment]
fixed the issue, i checked if the temp was null AFTER the loop. By putting it inside the for loop, the program will say out of bounds if it is a wrong position

**Comment by Aswan-A** [comment]
Issue not solved.

**Comment by Swassyman** [comment]
everyone is free to fix it and pull req

**Comment by Swassyman** [comment]
Issue has been solved

![image](https://github.com/user-attachments/assets/46b57c23-61e4-412f-a906-9084e9328219)
